/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HealthData {
    bmi?: number;
    waterIntakeMl: bigint;
    bmiCategory?: string;
    steps: bigint;
    timestamp: Time;
    caloriesBurned: bigint;
}
export type Time = bigint;
export interface backendInterface {
    addWaterIntake(amountMl: bigint): Promise<void>;
    calculateAndStoreBMI(heightCm: number, weightKg: number): Promise<[number, string]>;
    getUserData(): Promise<Array<HealthData>>;
    getWeeklyData(): Promise<Array<HealthData>>;
    recordDailyData(steps: bigint, waterIntakeMl: bigint, caloriesBurned: bigint): Promise<void>;
    resetDailyData(): Promise<void>;
}
import type { HealthData as _HealthData, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWaterIntake(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaterIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaterIntake(arg0);
            return result;
        }
    }
    async calculateAndStoreBMI(arg0: number, arg1: number): Promise<[number, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAndStoreBMI(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAndStoreBMI(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUserData(): Promise<Array<HealthData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyData(): Promise<Array<HealthData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyData();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyData();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordDailyData(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailyData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailyData(arg0, arg1, arg2);
            return result;
        }
    }
    async resetDailyData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDailyData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDailyData();
            return result;
        }
    }
}
function from_candid_HealthData_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthData): HealthData {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bmi: [] | [number];
    waterIntakeMl: bigint;
    bmiCategory: [] | [string];
    steps: bigint;
    timestamp: _Time;
    caloriesBurned: bigint;
}): {
    bmi?: number;
    waterIntakeMl: bigint;
    bmiCategory?: string;
    steps: bigint;
    timestamp: Time;
    caloriesBurned: bigint;
} {
    return {
        bmi: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.bmi)),
        waterIntakeMl: value.waterIntakeMl,
        bmiCategory: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bmiCategory)),
        steps: value.steps,
        timestamp: value.timestamp,
        caloriesBurned: value.caloriesBurned
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthData>): Array<HealthData> {
    return value.map((x)=>from_candid_HealthData_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
